"""RECIPE IMG New BLOB

Revision ID: 514243a4313e
Revises: e4213cde305d
Create Date: 2024-05-07 11:51:20.825893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '514243a4313e'
down_revision = 'e4213cde305d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_imgs', schema=None) as batch_op:
        batch_op.alter_column('img',
               existing_type=sa.VARCHAR(),
               type_=sa.LargeBinary(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_imgs', schema=None) as batch_op:
        batch_op.alter_column('img',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
