"""Updates constraint

Revision ID: 9a283079fd81
Revises: 8c85b3e82fa4
Create Date: 2024-04-30 14:53:23.994414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a283079fd81'
down_revision = '8c85b3e82fa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_constraint('ingredient_recipe_uc', type_='unique')
        batch_op.create_unique_constraint('ingredient_recipe_uc', ['food_id', 'recipe_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_constraint('ingredient_recipe_uc', type_='unique')
        batch_op.create_unique_constraint('ingredient_recipe_uc', ['id', 'recipe_id'])

    # ### end Alembic commands ###
