"""Update Recipe

Revision ID: c87636cde824
Revises: 9a283079fd81
Create Date: 2024-05-06 17:16:48.156131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c87636cde824'
down_revision = '9a283079fd81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('prep_time', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('recipe_img', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('source')
        batch_op.drop_column('recipe_img')
        batch_op.drop_column('prep_time')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
